version: '2'
services:
  ###
  api-gateway:
    image: vustrong/vicourses-apigateway
    networks:
      - vicourses-network
    ports:
      - 8000:8080

  ###
  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    env_file:
      - rabbitmq/.env
    networks:
      - vicourses-network
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: "exit 0"
      timeout: 10s

  ###
  mysql:
    build: 
      context: ./db/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - db/mysql/.env
    ports:
      - "13306:3306"
    volumes:
      - mysqldb_data:/var/lib/mysql
    networks:
      - vicourses-network
    healthcheck:
      test: "exit 0"

  ###
  auth-service:
    build:
      context: ./services/auth_service
    networks:
      - vicourses-network
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always

  ###
  email-service:
    image: vustrong/vicourses-emailservice
    networks:
      - vicourses-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    env_file:
      - services/email_service/.env

networks:
  vicourses-network:
    driver: bridge

volumes:
  mysqldb_data: