version: '2'
services:
  ###
  api-gateway:
    image: vustrong/vicourses-apigateway
    networks:
      - vicourses-network
    ports:
      - 8000:8080

  ###
  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    env_file:
      - rabbitmq/.env
    networks:
      - vicourses-network
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: "exit 0"
      timeout: 10s

  ###
  mysql:
    image: mysql:8.4.0
    command: ["mysqld", "--mysql-native-password=ON"]
    restart: always
    env_file:
      - db/mysql/.env
    ports:
      - "13306:3306"
    volumes:
      - mysqldb_data:/var/lib/mysql
      - ./db/mysql/scripts:/docker-entrypoint-initdb.d
    networks:
      - vicourses-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  ###
  auth-service:
    image: vustrong/vicourses-authservice
    env_file:
      - services/auth_service/.env
    volumes:
      - ./services/auth_service/private.key:/app/private.key
      - ./services/auth_service/public.key:/app/public.key
    networks:
      - vicourses-network
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always

  ###
  email-service:
    image: vustrong/vicourses-emailservice
    networks:
      - vicourses-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    env_file:
      - services/email_service/.env

networks:
  vicourses-network:
    driver: bridge

volumes:
  mysqldb_data: