version: '2'
services:
  ###
  vicourses-client-web:
    build:
      context: .
      args:
        - BACKEND_URL=http://localhost:8000
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
        - NEXT_PUBLIC_PAYPAL_CLIENT_ID=${NEXT_PUBLIC_PAYPAL_CLIENT_ID}
        - NEXT_PUBLIC_PAYPAL_LOGIN_AUTHORIZATION_URL=${NEXT_PUBLIC_PAYPAL_LOGIN_AUTHORIZATION_URL}
        - NEXT_PUBLIC_PAYPAL_LOGIN_RETURN_URL=${NEXT_PUBLIC_PAYPAL_LOGIN_RETURN_URL}
      network: host
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://api-gateway:8080
      - AUTH_URL=http://localhost:4000
    ports:
      - 4000:4000
    networks:
      - vicourses-network

networks:
  vicourses-network:
    name: vicourses-network
    external: true