filebeat.inputs:
  - type: filestream
    id: vicourses-services-filestream-id
    paths:
      - "/var/log/services/*.log"

output.elasticsearch:
  hosts: ["https://elasticsearch01:9200"]
  username: "elastic"
  password: "123456"
  ssl.certificate_authorities: ["certs/ca/ca.crt"]
  index: "vicourses-services-logs"

setup.template.name: "vicourses-services-logs"
setup.template.pattern: "vicourses-services-logs"