# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: discount-service

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/services/DiscountService/**"
      - ".github/workflows/discount-service.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "backend/services/DiscountService/**"
      - ".github/workflows/discount-service.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: backend/services/DiscountService
      run: dotnet restore "./DiscountService.API/DiscountService.API.csproj"
    - name: Build
      working-directory: backend/services/DiscountService/DiscountService.API
      run: dotnet build "DiscountService.API.csproj" --no-restore
    - name: Test
      working-directory: backend/services/DiscountService/DiscountService.FunctionalTests
      run: dotnet test

    - name: Build images
      working-directory: backend/services/DiscountService
      run: docker build -f DiscountService.API/Dockerfile -t vustrong/vicourses-discountservice .
    - name: Push images
      run: |-
        docker login -u vustrong -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push vustrong/vicourses-discountservice
