name: no-build
on:
  push:
    branches: [ "main" ]
    paths:
      - "deployments/**"
      - ".gitattributes"
      - "README.md"
      - "images/**"
      - ".github/workflows/no-build.yml"
      - "frontend/vicourses_mobile_app/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "deployments/**"
      - ".gitattributes"
      - "README.md"
      - "images/**"
      - ".github/workflows/no-build.yml"
      - "frontend/vicourses_mobile_app/**"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '
