# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: payment-service

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/services/PaymentService/**"
      - ".github/workflows/payment-service.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "backend/services/PaymentService/**"
      - ".github/workflows/payment-service.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: backend/services/PaymentService
      run: dotnet restore "./PaymentService.API/PaymentService.API.csproj"
    - name: Build
      working-directory: backend/services/PaymentService/PaymentService.API
      run: dotnet build "PaymentService.API.csproj" --no-restore

    - name: Build images
      working-directory: backend/services/PaymentService
      run: docker build -f PaymentService.API/Dockerfile -t vustrong/vicourses-paymentservice .
    - name: Push images
      run: |-
        docker login -u vustrong -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push vustrong/vicourses-paymentservice
