# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: search-service

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/services/SearchService/**"
      - ".github/workflows/search-service.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "backend/services/SearchService/**"
      - ".github/workflows/search-service.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: backend/services/SearchService
      run: dotnet restore "./SearchService.API/SearchService.API.csproj"
    - name: Build
      working-directory: backend/services/SearchService/SearchService.API
      run: dotnet build "SearchService.API.csproj" --no-restore

    - name: Build images
      working-directory: backend/services/SearchService
      run: docker build -f SearchService.API/Dockerfile -t vustrong/vicourses-searchservice .
    - name: Push images
      run: |-
        docker login -u vustrong -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push vustrong/vicourses-searchservice
