name: vicourses-admin-web

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/vicourses_admin_web/**"
      - ".github/workflows/vicourses-admin-web.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "frontend/vicourses_admin_web/**"
      - ".github/workflows/vicourses-admin-web.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21.x'
        cache: 'npm'
        cache-dependency-path: './frontend/vicourses_admin_web/package-lock.json'
    - name: Build
      working-directory: frontend/vicourses_admin_web
      run: |
        npm ci
        npm run build --if-present
