# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: wishlist-service

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/services/WishlistService/**"
      - ".github/workflows/wishlist-service.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "backend/services/WishlistService/**"
      - ".github/workflows/wishlist-service.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: backend/services/WishlistService
      run: dotnet restore "./WishlistService.API/WishlistService.API.csproj"
    - name: Build
      working-directory: backend/services/WishlistService/WishlistService.API
      run: dotnet build "WishlistService.API.csproj" --no-restore
    - name: Test
      working-directory: backend/services/WishlistService/WishlistService.UnitTests
      run: dotnet test

    - name: Build images
      working-directory: backend/services/WishlistService
      run: docker build -f WishlistService.API/Dockerfile -t vustrong/vicourses-wishlistservice .
    - name: Push images
      run: |-
        docker login -u vustrong -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push vustrong/vicourses-wishlistservice
